# Generated by Django 5.0.8 on 2026-06-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama')], max_length=20)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('base_url', models.URLField(blank=True)),
                ('selected_model', models.CharField(blank=True, max_length=255)),
                ('model_catalog', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('last_model_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'provider', 'name'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='budgets.llmproviderconfig'),
        ),
    ]
