# Generated by Django 5.0.8 on 2026-06-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_llmproviderconfig_analysisrun_provider_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="budgets.analysisrun",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
